import { Currency } from '../model/currency';

export const currencyList: Currency[] = [
  { name: 'AED', flag: '🇦🇪', countries: ['AE'] },
  { name: 'ARS', flag: '🇦🇷', countries: ['AR'] },
  { name: 'AUD', flag: '🇦🇺', countries: ['AU'] },
  { name: 'BHD', flag: '🇧🇭', countries: ['BH'] },
  { name: 'BMD', flag: '🇧🇲', countries: ['BM'] },
  { name: 'BRL', flag: '🇧🇷', countries: ['BR'] },
  { name: 'CAD', flag: '🇨🇦', countries: ['CA'] },
  { name: 'CLP', flag: '🇨🇱', countries: ['CL'] },
  {
    name: 'USD',
    flag: '🇺🇸',
    countries: [
      'US',
      'EC',
      'SV',
      'GU',
      'MP',
      'AS',
      'VI',
      'UM',
      'FM',
      'MH',
      'PW',
    ],
  },
  {
    name: 'EUR',
    flag: '🇪🇺',
    countries: [
      'AT',
      'BE',
      'CY',
      'EE',
      'FI',
      'FR',
      'DE',
      'GR',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MT',
      'NL',
      'PT',
      'SK',
      'SI',
      'ES',
    ],
  },
  { name: 'GBP', flag: '🇬🇧', countries: ['GB'] },
  { name: 'CHF', flag: '🇨🇭', countries: ['CH', 'LI'] },
  { name: 'CNY', flag: '🇨🇳', countries: ['CN'] },
  { name: 'CZK', flag: '🇨🇿', countries: ['CZ'] },
  { name: 'DKK', flag: '🇩🇰', countries: ['DK', 'FO', 'GL'] },
  { name: 'HKD', flag: '🇭🇰', countries: ['HK'] },
  { name: 'IDR', flag: '🇮🇩', countries: ['ID'] },
  { name: 'ILS', flag: '🇮🇱', countries: ['IL'] },
  { name: 'INR', flag: '🇮🇳', countries: ['IN'] },
  { name: 'JPY', flag: '🇯🇵', countries: ['JP'] },
  { name: 'KRW', flag: '🇰🇷', countries: ['KR'] },
  { name: 'KWD', flag: '🇰🇼', countries: ['KW'] },
  { name: 'LKR', flag: '🇱🇰', countries: ['LK'] },
  { name: 'MXN', flag: '🇲🇽', countries: ['MX'] },
  { name: 'MYR', flag: '🇲🇾', countries: ['MY'] },
  { name: 'NGN', flag: '🇳🇬', countries: ['NG'] },
  { name: 'NOK', flag: '🇳🇴', countries: ['NO', 'SJ'] },
  { name: 'NZD', flag: '🇳🇿', countries: ['NZ', 'CK', 'NU', 'TK'] },
  { name: 'PHP', flag: '🇵🇭', countries: ['PH'] },
  { name: 'PKR', flag: '🇵🇰', countries: ['PK'] },
  { name: 'PLN', flag: '🇵🇱', countries: ['PL'] },
  { name: 'RUB', flag: '🇷🇺', countries: ['RU'] },
  { name: 'SEK', flag: '🇸🇪', countries: ['SE'] },
  { name: 'SGD', flag: '🇸🇬', countries: ['SG'] },
  { name: 'THB', flag: '🇹🇭', countries: ['TH'] },
  { name: 'TRY', flag: '🇹🇷', countries: ['TR'] },
  { name: 'TWD', flag: '🇹🇼', countries: ['TW'] },
  { name: 'UAH', flag: '🇺🇦', countries: ['UA'] },
  { name: 'VND', flag: '🇻🇳', countries: ['VN'] },
  { name: 'ZAR', flag: '🇿🇦', countries: ['ZA'] },
];
